name: Build and Deploy Next.js site
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    ci-build:
        runs-on: ubuntu-latest
        steps:
            - name: リポジトリをチェックアウト
            uses: actions/checkout@v4  
            - name: Node.js のセットアップ
            uses: actions/setup-node@v4
            with:
                node-version: '20'
                cacha: 'npm'
            - name: setting pages
            uses: actions/configure-pages@v5
            with:
                static_site_generator:next
            - name: install dependencies
            run: npm ci
            - name: build
            run: npm run build
            - name: artifact
            uses: actions/upload-artifact@v3
            with:
                path: ./out
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: ci-build
        steps:
            - name: deploy artifact
            id: deployment
            uses: actions/deploy-artifact@v4
